name: CI

on:
  push:
    branches:
      - main
      - release
  pull_request:
    branches:
      - master
      - release
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      FULL_NAME: "Сиротина Елизавета"
      GROUP_NUMBER: "М3111"

    steps:
      - name: Print info
        run: |
          echo "ФИО: $FULL_NAME"
          echo "Номер группы: $GROUP_NUMBER"
          echo "Ник на GitHub: $GITHUB_ACTOR"
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          ref: feat/tests

      - name: Set up Python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unit tests
        run: |
          python -m unittest discover -s tests -p "*.py"

      - name: Install black
        run: |
          pip install black

      - name: Check code style
        run: black --check .

      - name: Format code (optional)
        run: black .
        if: ${{ failure() }}
